### ISSUE TITLE
[Feature Request] 可以预先提供一个术语表。在后续提取时忽略这个术语表中的人物或其它术语。重复词检测的时候也要考虑这个术语表。

### ISSUE THREAD

**Issue by PipeYume** [neavo/KeywordGacha#14]
使用第一次运行后得到的术语表的修正版本或者人工的术语表版本，作为第二次的输入。第二次运行时，自动判断提取的术语是否已经存在，如果已经存在则忽略。
增加第二次运行的准确性，减少第二次运行的干扰项和运行时间。

**Comment by neavo** [comment]
现在的版本里已经取消了重复词根检测的功能，理论上可以试用黑名单功能来实现上面描述的效果，可以尝试一下
不过现在版本的处理速度已经比较理想了，也没必要追求这点极限性能
