### ISSUE TITLE
[Issue] オレ/アタシ是自称，可以屏蔽了

### ISSUE THREAD

**Issue by PipeYume** [neavo/KeywordGacha#15]
![image](https://github.com/neavo/KeywordGacha/assets/81861009/90bcb662-1027-41fa-bec1-b8cb1010eecb)
![image](https://github.com/neavo/KeywordGacha/assets/81861009/904c0283-3d0c-498f-8c5b-a836c404fe4b)

**Comment by PipeYume** [comment]
![image](https://github.com/neavo/KeywordGacha/assets/81861009/7eb5db8b-cd0f-43cd-9b6b-0c23cc32e4d0)
还有爸爸也可以屏蔽了？

![image](https://github.com/neavo/KeywordGacha/assets/81861009/ba88ba80-2993-4abd-a11f-8e604a567589)
还有老太婆（bba）？

**Comment by PipeYume** [comment]
![image](https://github.com/neavo/KeywordGacha/assets/81861009/a6e0a423-7ce2-4d8e-a357-96bad88d7f89)

あんた/アンタ（你）

**Comment by PipeYume** [comment]
![image](https://github.com/neavo/KeywordGacha/assets/81861009/c18fb5b5-0dd4-4192-a572-6ac9114b02bb)

お前（你）

**Comment by PipeYume** [comment]
![image](https://github.com/neavo/KeywordGacha/assets/81861009/9c151164-ce63-4317-9154-9558dbf0b9d6)

貴方（您）

**Comment by PipeYume** [comment]
https://baijiahao.baidu.com/s?id=1787683825605525925

可以把这些都屏蔽了（

**Comment by neavo** [comment]
感谢反馈，能打字发一下吗，我 。。。不会日语，打不出回来

**Comment by PipeYume** [comment]
```json
{
  "私": "",
  "わたし": "",
  "わたくし": "",
  "あたし": "",
  "あたくし": "",
  "僕": "",
  "ぼく": "",
  "俺": "",
  "おれ": "",
  "我": "",
  "吾": "",
  "われ": "",
  "わし": "",
  "自分": "",
  "じぶん": "",
  "我辈": "",
  "わがはい": "",
  "拙者": "",
  "せっしゃ": "",
  "小生": "",
  "しょうせい": "",
  "予": "",
  "余": "",
  "よ": "",
  "わらわ": "",
  "うち": "",
  "わたす": "",
  "あなた": "",
  "あんた": "",
  "お前": "",
  "おまえ": "",
  "君": "",
  "きみ": "",
  "汝": "",
  "なんじ": "",
  "贵様": "",
  "きさま": "",
  "てめえ": "",
  "おのれ": "",
  "贵殿": "",
  "きでん": "",
  "彼": "",
  "かれ": "",
  "彼女": "",
  "かのじょ": "",
  "こいつ": "",
  "やつ": "",
  "あいつ": "",
  "ちゃん": "",
  "さん": "",
  "くん": "",
  "君くん": "",
  "様": "",
  "さま": "",
  "殿": "",
  "どの": "",
  "阁下": "",
  "かっか": "",
  "殿下": "",
  "でんか": "",
  "ワタシ": "",
  "ワタクシ": "",
  "アタシ": "",
  "アタクシ": "",
  "ボク": "",
  "オレ": "",
  "ワレ": "",
  "ワシ": "",
  "ジブン": "",
  "ワガハイ": "",
  "セッシャ": "",
  "ショウセイ": "",
  "ヨ": "",
  "ワラワ": "",
  "ウチ": "",
  "ワタス": "",
  "アナタ": "",
  "アンタ": "",
  "オマエ": "",
  "キミ": "",
  "ナンジ": "",
  "キサマ": "",
  "テメエ": "",
  "オノレ": "",
  "キデン": "",
  "カレ": "",
  "カノジョ": "",
  "コイツ": "",
  "ヤツ": "",
  "アイツ": "",
  "チャン": "",
  "サン": "",
  "クン": "",
  "サマ": "",
  "ドノ": "",
  "カッカ": "",
  "デンカ": ""
}
```

大概这些吧，把片假名写法也补上去了。因为有些小说的人称代词也会用片假名来写。

**Comment by neavo** [comment]
> ```json
> {
>   "私": "",
>   "わたし": "",
>   "わたくし": "",
>   "あたし": "",
>   "あたくし": "",
>   "僕": "",
>   "ぼく": "",
>   "俺": "",
>   "おれ": "",
>   "我": "",
>   "吾": "",
>   "われ": "",
>   "わし": "",
>   "自分": "",
>   "じぶん": "",
>   "我辈": "",
>   "わがはい": "",
>   "拙者": "",
>   "せっしゃ": "",
>   "小生": "",
>   "しょうせい": "",
>   "予": "",
>   "余": "",
>   "よ": "",
>   "わらわ": "",
>   "うち": "",
>   "わたす": "",
>   "あなた": "",
>   "あんた": "",
>   "お前": "",
>   "おまえ": "",
>   "君": "",
>   "きみ": "",
>   "汝": "",
>   "なんじ": "",
>   "贵様": "",
>   "きさま": "",
>   "てめえ": "",
>   "おのれ": "",
>   "贵殿": "",
>   "きでん": "",
>   "彼": "",
>   "かれ": "",
>   "彼女": "",
>   "かのじょ": "",
>   "こいつ": "",
>   "やつ": "",
>   "あいつ": "",
>   "ちゃん": "",
>   "さん": "",
>   "くん": "",
>   "様": "",
>   "さま": "",
>   "殿": "",
>   "どの": "",
>   "阁下": "",
>   "かっか": "",
>   "殿下": "",
>   "でんか": "",
>   "ワタシ": "",
>   "ワタクシ": "",
>   "アタシ": "",
>   "アタクシ": "",
>   "ボク": "",
>   "オレ": "",
>   "ワレ": "",
>   "ワシ": "",
>   "ジブン": "",
>   "ワガハイ": "",
>   "セッシャ": "",
>   "ワラワ": "",
>   "ウチ": "",
>   "ワタス": "",
>   "アナタ": "",
>   "アンタ": "",
>   "キミ": "",
>   "ナンジ": "",
>   "キサマ": "",
>   "テメエ": "",
>   "オノレ": "",
>   "キデン": "",
>   "カレ": "",
>   "カノジョ": "",
>   "コイツ": "",
>   "ヤツ": "",
>   "アイツ": "",
>   "チャン": "",
>   "サン": "",
>   "クン": ""
> }
> ```
> 
> 大概这些吧，把一些片假名写法也补上去了。因为有些小说的人称代词也会用片假名来写。

收到，谢谢，将在下个版本中加入默认黑名单

**Comment by neavo** [comment]
新版已加上 https://github.com/neavo/KeywordGacha/commit/8d0ab4930ee50ff2cfa0689d0bcb10252bab6141
