### ISSUE TITLE
[Feature Request] 除了直接出结果外，还可以生成可用于在线chatGPT的Prompt / 或者直接考虑用Web端+油猴脚本自动化

### ISSUE THREAD

**Issue by PipeYume** [neavo/KeywordGacha#20]
通过本地模型来获取粗略的结果，再通过免费的在线GPT来获取更加精确的结果。
这样子可以不使用昂贵的API服务，而通过免费的在线服务代替。
（这可能需要考率prompt的长度。）
（如果要更加自动化一点，油猴脚本是可以让chatGPT自动输入一些东西的？可以让油猴自动输入和总结？）

**Comment by PipeYume** [comment]
关于如何利用web端的ChatGPT，写了点代码。[GPT网页端支持示例.zip](https://github.com/user-attachments/files/16174628/GPT.zip)

其中：

ChatGPTWebSupport.js 根据 https://github.com/zsodur/chatgpt-api-by-browser-script/blob/master/tampermonkey-script.js 改了些代码。
是个油猴脚本。需要配合Disable-Content-Security-Policy插件使用 https://chromewebstore.google.com/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?pli=1
激活后可以连接到本地的服务端。

ChatGPTWebSupportServer.py 是本地服务端。用于将本地客户端发送的消息转发给油猴脚本以 在 chatGPT网页端 输入对话。同时将网页端的结果转化给本地客户端。

ChatGPTWebSupportLocalClient.py 是个例子，启动后可以输入任意prompt等待回复。
（具体的仓库内我不知道怎么弄。因为这个这个仓库是每个word分别处理。如果是GPT网页端，由于不考虑token的花销，可以考虑多个词作为prompt一起输入，但是不能异步多个请求。所以如果考虑集成进去需要改些东西。）


PS: web端可以开临时聊天，以快速清除每次跑的记录。
![image](https://github.com/neavo/KeywordGacha/assets/81861009/921b0015-8f32-4c2d-b275-c903b8dc19b4)

虽然有R18的限制，但是非R18文可用（
速度可能会很慢是个问题（

**Comment by neavo** [comment]
认真考虑了一下，还是认为这种算是hack的行为不应该由 KG 工具本身来支持，这样会让处理流程过于复杂
