### ISSUE TITLE
[Feature Request] 增加请求速率和超时时间的自定义设置

### ISSUE THREAD

**Issue by WeeAris** [neavo/KeywordGacha#3]
简单来说就是我本地跑模型太慢超时了，上API请求速率太快被拒了，所以希望增加这两个设置项。

**Comment by neavo** [comment]
已完成 https://github.com/neavo/KeywordGacha/commit/43d9d851071c47d9784043e7ec93eca356e8233a

**Comment by WeeAris** [comment]
> 已完成 [43d9d85](https://github.com/neavo/KeywordGacha/commit/43d9d851071c47d9784043e7ec93eca356e8233a)

一个建议，绝大多数OpenAI API兼容的接口都用429作为速率限制的错误状态码，能不能加一个判定，遇到状态码为429时不要马上重试，而是冷却一段时间。

**Comment by neavo** [comment]
> > 已完成 [43d9d85](https://github.com/neavo/KeywordGacha/commit/43d9d851071c47d9784043e7ec93eca356e8233a)
> 
> 一个建议，绝大多数OpenAI API兼容的接口都用429作为速率限制的错误状态码，能不能加一个判定，遇到状态码为429时不要马上重试，而是冷却一段时间。

新版中的 网络请求频率阈值 设置中加入了刚性的 QPS 限制，而且可以设为低于 1 的值，应该可以满足你的需求了

待确认 @WeeAris
