### ISSUE TITLE
建议运行ner之前检查配置文件等信息

### ISSUE THREAD

**Issue by jeshs** [neavo/KeywordGacha#33]
在运行前检查，避免运行ner后才出现接口不通、key失效或待处理文件格式错误等情况，浪费时间
1、运行前检查配置文件config.json的格式、key和api的有效性
2、运行前检查待处理文本的格式，例如：可能出现过待处理文本是json后缀但是内容不符合json格式的情况

**Comment by neavo** [comment]
好提议

前面一直在搞基础功能，没太在意细节，后续陆续不上这些体验细节

**Comment by neavo** [comment]
已完成 https://github.com/neavo/KeywordGacha/issues/33#issue-2420727851
