### ISSUE TITLE
哇qaq翻译报错

### ISSUE THREAD

**Issue by slvai1300000000** [neavo/KeywordGacha#39]
[09:48:56] INFO     [查找上下文] 已完成 ...
[09:48:56] INFO     即将开始执行 [词根还原] ...
[09:48:56] INFO     通过 规则还原 还原词根 - ガチ勢キタ, ガチ勢キタ
[09:48:56] INFO     [词根还原] 已完成 ...
[09:48:56] INFO     即将开始执行 [语法校验] ...
[09:48:56] INFO     通过 词语形态学 剔除词语 - PRODUCT - どうぞ
[09:48:56] INFO     [语法校验] 已完成 ...
[09:48:56] INFO     即将开始执行 [阈值筛选] ... 当前出现次数的筛选阈值设置为 3 ...
[09:48:56] INFO     [阈值筛选] 已完成 ... 出现次数 <= 3 的条目已剔除 ...
[09:48:56] INFO     即将开始执行 [词性判断] ...
WARNING [词性判断] 子任务执行失败，稍后将重试 ... Error code: 404 - {'error': 'Not found'}
                    Traceback (most recent call last):
                      File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 199, in
                    on_analyze_attribute_task_done
                        word = future.result()
                               ^^^^^^^^^^^^^^^
                      File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 170, in
                    analyze_attribute
                        usage, message, word.llmresponse_analyze_attribute = await self.request(prompt,
                    "\n".join(word.context), task_type, retry)
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 141, in request
                        completion = await self.openai_handler.chat.completions.create(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File
                    "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai\resources\chat\comple
                    tions.py", line 1295, in create
                        return await self._post(
                               ^^^^^^^^^^^^^^^^^
                      File
                    "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai\_base_client.py",
                    line 1826, in post
                        return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File
                    "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai\_base_client.py",
                    line 1519, in request
                        return await self._request(
                               ^^^^^^^^^^^^^^^^^^^^
                      File
                    "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai\_base_client.py",
                    line 1620, in _request
                        raise self._make_status_error_from_response(err.response) from None
                    openai.NotFoundError: Error code: 404 - {'error': 'Not found'}

**Comment by neavo** [comment]
看报错是接口地址填的不对，检查一下有没有多余的空格之类的

后续会在应用内增加检查接口功能

**Comment by MOs12322** [comment]
https://books.fishhawk.top/forum/656d60530286f15e3384fcf8 可以参照这里面的部属方式，甚至还有一个gui帮你操作。然后可以去llama.cpp这个项目更新一下llama文件架，防止有的模型框架没被适配，例如gemma2

**Comment by neavo** [comment]
> https://books.fishhawk.top/forum/656d60530286f15e3384fcf8 可以参照这里面的部属方式，甚至还有一个gui帮你操作。然后可以去llama.cpp这个项目更新一下llama文件架，防止有的模型框架没被适配，例如gemma2

其实我打包了一个配套的一键包 https://github.com/neavo/KeywordGachaServer

**Comment by neavo** [comment]
> [09:48:56] INFO [查找上下文] 已完成 ... [09:48:56] INFO 即将开始执行 [词根还原] ... [09:48:56] INFO 通过 规则还原 还原词根 - ガチ勢キタ, ガチ勢キタ [09:48:56] INFO [词根还原] 已完成 ... [09:48:56] INFO 即将开始执行 [语法校验] ... [09:48:56] INFO 通过 词语形态学 剔除词语 - PRODUCT - どうぞ [09:48:56] INFO [语法校验] 已完成 ... [09:48:56] INFO 即将开始执行 [阈值筛选] ... 当前出现次数的筛选阈值设置为 3 ... [09:48:56] INFO [阈值筛选] 已完成 ... 出现次数 <= 3 的条目已剔除 ... [09:48:56] INFO 即将开始执行 [词性判断] ... WARNING [词性判断] 子任务执行失败，稍后将重试 ... Error code: 404 - {'error': 'Not found'} Traceback (most recent call last): File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 199, in on_analyze_attribute_task_done word = future.result() ^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 170, in analyze_attribute usage, message, word.llmresponse_analyze_attribute = await self.request(prompt, "\n".join(word.context), task_type, retry) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\model\LLM.py", line 141, in request completion = await self.openai_handler.chat.completions.create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai\resources\chat\comple tions.py", line 1295, in create return await self._post( ^^^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai_base_client.py", line 1826, in post return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai_base_client.py", line 1519, in request return await self._request( ^^^^^^^^^^^^^^^^^^^^ File "F:\KeywordGacha_DEV_20240724_104208\KeywordGacha\env\Lib\site-packages\openai_base_client.py", line 1620, in _request raise self._make_status_error_from_response(err.response) from None openai.NotFoundError: Error code: 404 - {'error': 'Not found'}

所以最后问题解决了吗
