### ISSUE TITLE
大大，可以增加对BallonsTranslator json的日语的翻译吗

### ISSUE THREAD

**Issue by asdads123** [neavo/KeywordGacha#55]
大大，可以增加对BallonsTranslator json的日语的翻译吗

**Comment by neavo** [comment]
> 大大，可以增加对BallonsTranslator json的日语的翻译吗

可以贴个例子上来看看

**Comment by YuGhi-bug** [comment]
BallonsTranslator 可以output txt
![image](https://github.com/user-attachments/assets/2688dfc5-2255-4b06-a3f7-8cf48e9a4d43)


> 大大，可以增加对BallonsTranslator json的日语的翻译吗

**Comment by neavo** [comment]
> > 大大，可以增加对BallonsTranslator json的日语的翻译吗
> 
> BallonsTranslator 可以output txt ![image](https://private-user-images.githubusercontent.com/65033074/378169783-2688dfc5-2255-4b06-a3f7-8cf48e9a4d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzkwMTEsIm5iZiI6MTczMTIzODcxMSwicGF0aCI6Ii82NTAzMzA3NC8zNzgxNjk3ODMtMjY4OGRmYzUtMjI1NS00YjA2LWEzZjctOGNmNDhlOWE0ZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDExMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YTFjOWZkYWE3ODUxNzg2YWMwOWU4ZDlkZThjMGMzNjA2MzE1MjFhNzdjM2QwMWFlMDkzODRhYmIzMjc4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a-EQuYZJOt0SHeeO1EE_Lb8cR0JIHp4MdTwbuXlTGms)
> 
> [imgtrans_重騎_source.txt](https://github.com/user-attachments/files/17449650/imgtrans_._source.txt)
> 
> > > 大大，可以增加对BallonsTranslator json的日语的翻译吗
> > 
> > 
> > 可以传个文件上来看看
> > [imgtrans_重騎.json](https://github.com/user-attachments/files/17449647/imgtrans_.json)

既然能输出纯文本直接跑纯文本就可以了吧
