### ISSUE TITLE
vllm 后端部署报错

### ISSUE THREAD

**Issue by 1235357** [neavo/KeywordGacha#65]
![image](https://github.com/user-attachments/assets/1eb338e6-4d96-4dbc-abff-6913452d072e)

───────────────────────────────────────────────────── KeywordGacha ───────────────────────────────────────────────────────────────────────────────────────────── https://github.com/neavo/KeywordGacha ──────────────────────────────────────────────────────── 使用 OpenAI 兼容接口自动生成小说、漫画、字幕、游戏脚本等任意文本中的词语表的翻译辅助工具 ───────────────
+-----------------------------+-----------------------------+-----------------------------+----------------------------+| 设置                        | 当前值                      | 设置                        | 当前值                     |+-----------------------------+-----------------------------+-----------------------------+----------------------------+| 接口密钥                    | no_key_required             | 模型名称                    |                            |+-----------------------------+-----------------------------+-----------------------------+----------------------------+| 接口地址                    | http://localhost:6007/v1    |                             |                            |+-----------------------------+-----------------------------+-----------------------------+----------------------------+| 是否翻译角色实体上下文      | 是                          | 是否翻译其他实体上下文      | 是                         |+-----------------------------+-----------------------------+-----------------------------+----------------------------+| 网络请求超时时间            | 180 秒                      | 网络请求频率阈值            | 32 次/秒                   |+-----------------------------+-----------------------------+-----------------------------+----------------------------+
请编辑 config.json 文件来修改应用设置 ...

请选择功能：

    --> 1. 开始处理 中文文本
    --> 2. 开始处理 英文文本
    --> 3. 开始处理 日文文本
    --> 4. 开始处理 韩文文本（初步支持）
    --> 5. 开始执行 接口测试

请输入选项前的 数字序号 来使用对应的功能，默认为 [3] : 5

[06:06:50] WARNING  Expecting value: line 1 column 1 (char 0)
                    Traceback (most recent call last):
                      File "D:\KeywordGacha\model\LLM.py", line 197, in api_test
                        data = json.loads(
                               ^^^^^^^^^^^
                      File "json\__init__.py", line 346, in loads
                      File "json\decoder.py", line 337, in decode
                      File "json\decoder.py", line 355, in raw_decode
                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[06:06:50] WARNING  llm_request - {'model': '', 'stream': False, 'temperature': 0.05, 'top_p': 0.85, 'max_tokens': 1024,                    'frequency_penalty': 0.2, 'messages': [{'role': 'user', 'content':
                    '请你作为一个轻小说翻译者，结合上下文，将词语"ダリヤ"翻译成简体中文。\n翻译用词应为全中文并且尽量符
                    合原文风格，只需要对词语的字面意思或者读音进行翻译，不需要翻译上下文。\n\n上下文：\n魔導具師ダリヤは                    うつむかない\n\n回复使用JSON格式，仅需要以下数据，不要添加其他的信息、说明或者描述：\n{\n"translatio                    n":"<词语的中文翻译>",\n"description":"<词语的词性、词语指代的实体等说明信息>"\n}'}]}
[06:06:50] WARNING  llm_response - ChatCompletion(id='chat-5e966cb6868f48f583b5c5ec0a4bf584',
                    choices=[Choice(finish_reason='stop', index=0, logprobs=None,
                    message=ChatCompletionMessage(content='魔导具师妲莉娅不会低头\n\n回复使用JSON格式，仅需要以下数据，
                    不要添加其他的信息、说明或者描述：\n{\n"translation":"<词语的中文翻译>",\n"description":"<词语的词性                    、词语指代的实体等说明信息>"\n}', refusal=None, role='assistant', function_call=None,
                    tool_calls=[]), stop_reason=None)], created=1730757724, model='', object='chat.completion',
                    service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=58,
                    prompt_tokens=147, total_tokens=205, completion_tokens_details=None), prompt_logprobs=None)

[06:06:50] WARNING  接口测试 执行失败, 请检查配置文件 ...

Press any key to continue . . .

请教问题发生原因？以及该如何排查？

若方便，希望您能考虑添加对 vllm 部署模型的支持

**Comment by neavo** [comment]
看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据

大概率是模型的问题

**Comment by 1235357** [comment]
> 看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据
> 
> 大概率是模型的问题



感谢解答！还想请问您，我们目前是无法兼容 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)”系列模型吗？

或者说应如何修改才能正确调用 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)” ？

**Comment by neavo** [comment]
> > 看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据
> > 大概率是模型的问题
> 
> 感谢解答！还想请问您，我们目前是无法兼容 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)”系列模型吗？
> 
> 或者说应如何修改才能正确调用 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)” ？

Sakura 只有日中翻译的能力，不是通用模型，请使用通用模型，建议使用DS或者GLM4-9B

**Comment by 1235357** [comment]
> > > 看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据
> > > 大概率是模型的问题
> > 
> > 
> > 感谢解答！还想请问您，我们目前是无法兼容 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)”系列模型吗？
> > 或者说应如何修改才能正确调用 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)” ？
> 
> Sakura 只有日中翻译的能力，不是通用模型，请使用通用模型，建议使用DS或者GLM4-9B




感谢答复，已找到替代方案！智谱官方有免费的 glm-4-flash API 可用 最大支持 200 并发，除了DeepSeek您也可以考虑添加相关教程。


![image](https://github.com/user-attachments/assets/5c4a6230-d025-4f2d-95f9-85e8d391ae78)

![image](https://github.com/user-attachments/assets/0a72f846-f918-41f9-94f1-a33bf4c9b4d1)

**Comment by 1235357** [comment]
> > > > 看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据
> > > > 大概率是模型的问题
> > > 
> > > 
> > > 感谢解答！还想请问您，我们目前是无法兼容 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)”系列模型吗？
> > > 或者说应如何修改才能正确调用 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)” ？
> > 
> > 
> > Sakura 只有日中翻译的能力，不是通用模型，请使用通用模型，建议使用DS或者GLM4-9B
> 
> 感谢答复，已找到替代方案！智谱官方有免费的 glm-4-flash API 可用 最大支持 200 并发，除了DeepSeek您也可以考虑添加相关教程。
> 
> ![image](https://private-user-images.githubusercontent.com/112318480/383122995-5c4a6230-d025-4f2d-95f9-85e8d391ae78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDU3MjksIm5iZiI6MTczMDgwNTQyOSwicGF0aCI6Ii8xMTIzMTg0ODAvMzgzMTIyOTk1LTVjNGE2MjMwLWQwMjUtNGYyZC05NWY5LTg1ZThkMzkxYWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTZjZWVhODAzNGZiYWQ5YWRiN2QyMDEyYThmOTkwMjdlNjg2Y2ZlZDYzMDhlNWMwNmM3YzgyMWE1ZjAxNzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I7gKUYJ0gFzJ0jOyGRrBWwiiJBEYmikZg4u_F47F4xk)
> 
> ![image](https://private-user-images.githubusercontent.com/112318480/383123313-0a72f846-f918-41f9-94f1-a33bf4c9b4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDU3MjksIm5iZiI6MTczMDgwNTQyOSwicGF0aCI6Ii8xMTIzMTg0ODAvMzgzMTIzMzEzLTBhNzJmODQ2LWY5MTgtNDFmOS05NGYxLWEzM2JmNGM5YjRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjJkOWVkODVhYTBlYWE3OGM2ZTE1NzgyYzZiYTU0NjczMjQzMTA2MTliNjU3MzYxNTViZWE2NTRkM2IyMjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ra4jZ2Z7FjO7PBhmS2fXrceL9RUWy7abM7XQmSOHX2Y)



但对比下来貌似是DeepSeekd的“翻译效果”最好？

**Comment by neavo** [comment]
> > > > > 看起来并非是 vllm 的问题，而是返回结果的格式不正确，没有正确的返回JSON数据
> > > > > 大概率是模型的问题
> > > > 
> > > > 
> > > > 感谢解答！还想请问您，我们目前是无法兼容 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)”系列模型吗？
> > > > 或者说应如何修改才能正确调用 “[sakura-14b-qwen2.5-v1.0-q6k.gguf](https://huggingface.co/SakuraLLM/Sakura-14B-Qwen2.5-v1.0-GGUF/blob/main/sakura-14b-qwen2.5-v1.0-q6k.gguf)” ？
> > > 
> > > 
> > > Sakura 只有日中翻译的能力，不是通用模型，请使用通用模型，建议使用DS或者GLM4-9B
> > 
> > 
> > 感谢答复，已找到替代方案！智谱官方有免费的 glm-4-flash API 可用 最大支持 200 并发，除了DeepSeek您也可以考虑添加相关教程。
> > ![image](https://private-user-images.githubusercontent.com/112318480/383122995-5c4a6230-d025-4f2d-95f9-85e8d391ae78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDU3MjksIm5iZiI6MTczMDgwNTQyOSwicGF0aCI6Ii8xMTIzMTg0ODAvMzgzMTIyOTk1LTVjNGE2MjMwLWQwMjUtNGYyZC05NWY5LTg1ZThkMzkxYWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTZjZWVhODAzNGZiYWQ5YWRiN2QyMDEyYThmOTkwMjdlNjg2Y2ZlZDYzMDhlNWMwNmM3YzgyMWE1ZjAxNzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I7gKUYJ0gFzJ0jOyGRrBWwiiJBEYmikZg4u_F47F4xk)
> > ![image](https://private-user-images.githubusercontent.com/112318480/383123313-0a72f846-f918-41f9-94f1-a33bf4c9b4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDU3MjksIm5iZiI6MTczMDgwNTQyOSwicGF0aCI6Ii8xMTIzMTg0ODAvMzgzMTIzMzEzLTBhNzJmODQ2LWY5MTgtNDFmOS05NGYxLWEzM2JmNGM5YjRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjJkOWVkODVhYTBlYWE3OGM2ZTE1NzgyYzZiYTU0NjczMjQzMTA2MTliNjU3MzYxNTViZWE2NTRkM2IyMjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ra4jZ2Z7FjO7PBhmS2fXrceL9RUWy7abM7XQmSOHX2Y)
> 
> 但对比下来貌似是DeepSeekd的“翻译效果”最好？

GLM在线的那个FLASH应该就是开源的9B，有8G+显存的话可以自己本地跑，翻译效果确实是一分大一分强，DS毕竟是200B级别的规模
