### ISSUE TITLE
TypeError: read_json_file() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by snowandrain** [neavo/KeywordGacha#68]
![image](https://github.com/user-attachments/assets/dcd034fd-6831-48f3-aa59-d862e4a1386c)
![image](https://github.com/user-attachments/assets/69e99173-a090-43e7-80f6-7e5f4c810e72)
参数language是不是要去掉？

**Comment by neavo** [comment]
> ![image](https://private-user-images.githubusercontent.com/22421823/385196741-dcd034fd-6831-48f3-aa59-d862e4a1386c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDExOTEsIm5iZiI6MTczMTQwMDg5MSwicGF0aCI6Ii8yMjQyMTgyMy8zODUxOTY3NDEtZGNkMDM0ZmQtNjgzMS00OGYzLWFhNTktZDg2MmU0YTEzODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZTJiMjA3M2E2NmE3MGE2M2U3ZDlmYjAxNzA2Yjc1MzQ2OWFjMDM0Y2RhYzM0MWEzMDJlN2UxMTY4MjNjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6BGDVJr502pqHiyCEadPoeku6KEIiSaMST5Jw9fQPZc) ![image](https://private-user-images.githubusercontent.com/22421823/385196893-69e99173-a090-43e7-80f6-7e5f4c810e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDExOTEsIm5iZiI6MTczMTQwMDg5MSwicGF0aCI6Ii8yMjQyMTgyMy8zODUxOTY4OTMtNjllOTkxNzMtYTA5MC00M2U3LTgwZjYtN2U1ZjRjODEwZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2FhYjUxNjhjMzIxMzViN2Y4NWFhYmM3ZDQwNGIxZTNlOTA0Njk4MTNkZDdhNjFmMDM2M2MzZWVhZmMxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D7ImeqIXb_kv1tjKkV1kemZlBlQRT3mpTOTOarE-my8) 参数language是不是要去掉？

是的，抱歉，是我漏掉了

**Comment by neavo** [comment]
> ![image](https://private-user-images.githubusercontent.com/22421823/385196741-dcd034fd-6831-48f3-aa59-d862e4a1386c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDI5ODMsIm5iZiI6MTczMTQwMjY4MywicGF0aCI6Ii8yMjQyMTgyMy8zODUxOTY3NDEtZGNkMDM0ZmQtNjgzMS00OGYzLWFhNTktZDg2MmU0YTEzODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMzhiYTM3MDA3MDlkYmI4YmRlYjhiM2ExOGEzMDAwZTY0YjIwZTMwZWU4YTliMTEyZjQzNjg5Yzk4YTBlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-ptitrSwzySXKR-bM_FqhRVNPNOgvxsFA7wfLlV7UL4) ![image](https://private-user-images.githubusercontent.com/22421823/385196893-69e99173-a090-43e7-80f6-7e5f4c810e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDI5ODMsIm5iZiI6MTczMTQwMjY4MywicGF0aCI6Ii8yMjQyMTgyMy8zODUxOTY4OTMtNjllOTkxNzMtYTA5MC00M2U3LTgwZjYtN2U1ZjRjODEwZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjNmYzU5NDgwNWM0ZmU0OWRmZmVkMTgxMDkyMDAyYWJiM2EwMjBkMmQ5YmY5YmQ0MTY0ZjZhMmNlMzE4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YDRNPYHScEfyqEI5omSAdZ9vuW-oK92AYlMxXiBtTz8) 参数language是不是要去掉？

https://github.com/neavo/KeywordGacha/releases/tag/MANAUL_BUILD_v0.5.4 已修
