### ISSUE TITLE
GitHub上的文件是不是损坏了，我下了两遍都这样

### ISSUE THREAD

**Issue by thyme-c** [neavo/KeywordGacha#79]
![image](https://github.com/user-attachments/assets/326bbff2-174d-4903-8e21-cbee79ad887a)

**Comment by neavo** [comment]
> ![image](https://private-user-images.githubusercontent.com/71761806/398584020-326bbff2-174d-4903-8e21-cbee79ad887a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDAxODQsIm5iZiI6MTczNTEzOTg4NCwicGF0aCI6Ii83MTc2MTgwNi8zOTg1ODQwMjAtMzI2YmJmZjItMTc0ZC00OTAzLThlMjEtY2JlZTc5YWQ4ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDNjOTAxNTY0OGQ2OGQ4MzI0ZmE1MTMzOGNmMmRkNmNmMTllNDBhNWU0M2Y3MDMwNzk0N2I4NDA5MWQ3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FFArug3OfrtUwjFCiUVKfZRSVzvNErJ86sU4v-m3mwg)

更新解压软件到最新版本，还不行就换bandizip的最新版本

**Comment by thyme-c** [comment]
> > ![image](https://private-user-images.githubusercontent.com/71761806/398584020-326bbff2-174d-4903-8e21-cbee79ad887a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDAxODQsIm5iZiI6MTczNTEzOTg4NCwicGF0aCI6Ii83MTc2MTgwNi8zOTg1ODQwMjAtMzI2YmJmZjItMTc0ZC00OTAzLThlMjEtY2JlZTc5YWQ4ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDNjOTAxNTY0OGQ2OGQ4MzI0ZmE1MTMzOGNmMmRkNmNmMTllNDBhNWU0M2Y3MDMwNzk0N2I4NDA5MWQ3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FFArug3OfrtUwjFCiUVKfZRSVzvNErJ86sU4v-m3mwg)
> 
> 更新解压软件到最新版本，或者用 bandizip 的最新版本

用bandizip解压成功了谢谢。最新7z都不行😖

**Comment by neavo** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/71761806/398584020-326bbff2-174d-4903-8e21-cbee79ad887a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDAxODQsIm5iZiI6MTczNTEzOTg4NCwicGF0aCI6Ii83MTc2MTgwNi8zOTg1ODQwMjAtMzI2YmJmZjItMTc0ZC00OTAzLThlMjEtY2JlZTc5YWQ4ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE1MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDNjOTAxNTY0OGQ2OGQ4MzI0ZmE1MTMzOGNmMmRkNmNmMTllNDBhNWU0M2Y3MDMwNzk0N2I4NDA5MWQ3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FFArug3OfrtUwjFCiUVKfZRSVzvNErJ86sU4v-m3mwg)
> > 
> > 
> > 更新解压软件到最新版本，或者用 bandizip 的最新版本
> 
> 用bandizip解压成功了谢谢。最新7z都不行😖

最新的 7z 应该是可以的，因为就是用 7z 压的，只是用的是（相对）比较新的 LZMA2 算法，所以要新版本
